baseURL = 'https://danroscigno.github.io/recipe-hugo'
languageCode = 'en-us'
title = 'Recipes'
summaryLength = 30
disableKinds = ["taxonomy"]

[markup]
highlight.noClasses = false

[markup.goldmark.renderer]
# ensures html inside markdown is allowed to render
unsafe = true

[[module.imports]]
path = 'github.com/bglw/alto-as-module'
